### PR TITLE
Cp7 user authorization

### PR DESCRIPTION
**Pull request by slyarboro**
Description: Implemented Authorization for Topics and Bookmarks
Test Coverage: 336 / 387 LOC (86.82%) covered.

### CODE REVIEW

**Comment by wonderwoman13** [comment]
@slyarboro super great job here. I added a commit that turned on your Test coverage calculation. Going forward, look at the description I edited above. Please do that :) Merging!

**Comment by slyarboro** [comment]
Word.

Loves me a good Test coverage calculation. How did you know?

In regards to said description, would you be a darling and elaborate on the _**that**_ (of _"do that"_)? 
One of the following, perhaps?
- Logic?
- Content?
- Phrasing?
- Test coverage inclusive?

**Comment by wonderwoman13** [comment]
When you pull down Master and run your tests, the % will be outputted now :)

"Do that" meant please model your Description on your future PRs like I did above. Thank you! @slyarboro

**Comment by slyarboro** [comment]
For real? Das tight. You smart.
Excellent. _That_, I can do!

Domo.

**Pull request merged**
